### ISSUE TITLE
Issue in tibble output printing

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/engineering-shiny-book#147]
e.g. https://engineering-shiny.org/successfulshinyapp.html

![Screenshot 2020-04-27 at 22 08 22](https://user-images.githubusercontent.com/17936236/80416056-c9013d00-88d3-11ea-95ac-cc756f523a70.png)

AFAIK, it's an issue of XQuartz/xterm installation on the GA machine, investigating rn.

**Comment by ColinFay** [comment]
That doesn't seem to be Mac OS only, I've built the book with Ubuntu and it does not solve the issue

**Comment by ColinFay** [comment]
@Robinlovelace @Nowosad do you happen to have met this issue while rendering geocompr with Github Actions?

**Comment by ColinFay** [comment]
Also pinging the Markdown grand-master @cderv

**Comment by cderv** [comment]
I think you have this because the crayon feature is activated during your rmarkdown document. ANSI colors are great in the terminal but not so great in HTML output.
Is is activated on purpose ? 
I think it should not be the case in CI rendering... 

Anyway, you can deactivate the coloring explicitly with the option `crayon.enabled = FALSE`. Or you can have ANSI coloring modified to HTML coloring if you like. See https://github.com/r-lib/crayon/issues/24#issuecomment-581068792. This issue will sum up what you encounter I think and link to other issue on this topic. 

Hope it helps.

**Comment by ColinFay** [comment]
@cderv that worked, thanks!!!

That was enabled by default :)

**Comment by cderv** [comment]
> That was enabled by default :)

If not activated by you explicitly it should not be activated for knitr rendering. You should not have to opt out of this in bookdown project or in GHA Workflow. I think this need to be looked into. 
I'll try on a dummy bookdown to see. 
Tell me if locally you have the issue when you render your book.

**Comment by ColinFay** [comment]
@cderv no, I don't have this issue locally, and I didn't have it when the rendering was done with Travis

**Comment by fmichonneau** [comment]
Maybe it's because of this https://github.com/r-lib/actions/blob/master/setup-r/action.yml#L14

**Comment by cderv** [comment]
Yes indeed! 
Crayon is activated explicitly here. Thank you @fmichonneau !

Is it deactivated in bookdown actions or Other actions that deal With rmarkdown rendering?

**Comment by cderv** [comment]
> Is it deactivated in bookdown actions or Other actions that deal With rmarkdown rendering?

Ok. I think it should be done this way in here
https://github.com/ThinkR-open/engineering-shiny-book/blob/0d487feafe9c522dd747c1fbdbd5ed181ed5c5e2/.github/workflows/deploy_bookdown.yml#L18

```yaml
- uses: r-lib/actions/setup-r@v1
  with:
    crayon.enabled: 'FALSE'
```
if i understand GHA correctly.
