### ISSUE TITLE
renv for shiny modules

### ISSUE THREAD

**Issue by ardeeshany** [ThinkR-open/engineering-shiny-book#274]
Hi,

Thanks for the amazing book. I read your section 11.2 about `renv` and was wondering if there is any best practice of using `renv` in the level of reusable shiny modules that you would want to suggest or include in that section. Imagine we have developed many shiny modules (each of them is in an standalone R-package format with an specific renv) and need to be combined to create to create a shiny app. How can we combine those renv dependencies to create the shiny app?

**Comment by ColinFay** [comment]
Hey @ardeeshany,

Unfortunately, this is not something you can do right now but this is not because of {shiny} modules but because of the way {renv} and R works. 

At the time of writing these lines, there is no reliable way to share the dep graph along the package: even if I'm using {renv} to build a package, whenever I'm going to distribute this package with module functions in it, it will be treated as a standard package. 

As far as I know, there is no way, for example, to build a module with Shiny 1.5.0, update R to the newest version of shiny, then use the previously created module with Shiny 1.5.0 in it: for the same app, you need to either use 1.5.0, or 1.6.0, but not mix both. 

Let me know if that answers your question, 
Colin

**Comment by ardeeshany** [comment]
@ColinFay 
Thanks for the complete answer.
